security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    #access_denied_url: /unauthorized

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main: # change this in fos_user in config.yml as well
            pattern: ^/
            form_login:
                provider: all
                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check
                # login success redirecting options
                always_use_default_target_path: true
                default_target_path: /clients
                use_referer: false
            http_basic:
              provider: fos_userbundle
            anonymous: true
            logout: true

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_ADMIN }
