services:
  controller.main:
    class:     Clieman\Controllers\MainController
    calls:
      - [setContainer, ["@service_container"]]

  controller.clients:
    class:     Clieman\Controllers\ClientsController
    calls:
      - [setContainer, ["@service_container"]]

  controller.projects:
    class:     Clieman\Controllers\ProjectsController
    calls:
      - [setContainer, ["@service_container"]]
